# [START runtime]
runtime: nodejs
env: flex
# [END runtime]

manual_scaling:
  instances: 1
resources:
  cpu: .9
  memory_gb: 0.98
  disk_size_gb: 10

# [START handlers]
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301
  - url: /
    static_dir: build
    secure: always
    redirect_http_response_code: 301
  # [END handlers]
